name: Test app

on:
  pull_request:
    branches: ["main"]

env:
  NODE_VERSION: "24.x"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "Test app"
        shell: bash
        run: |
          pushd '.'
          npm install
          npm run test
          popd
